# -*- coding: utf-8 -*-
"""Quantitative Finance Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kg2m5cHnMXMFR58XYTrq6664qPhBNoRf
"""

# Quant Finance Libraries Installation

!pip install numpy
!pip install pandas
!pip install yfinance
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn
!pip install statsmodels
!pip install scipy
!pip install quantlib

# Importing Libraries

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from statsmodels.tsa.stattools import coint
import statsmodels.api as sm
from scipy import stats

# Sample Data Downloading
ticker = 'AAPL'  # Apple Inc. stock as an example
start_date = '2024-06-01'
end_date = '2024-07-01'
data = yf.download(ticker, start=start_date, end=end_date)

# Display the first 5 rows of the data
data.head()

"""What is Open High Low Close Adj Close Volume?

Open: The price at which a security first trades upon the opening of an exchange on a given trading day. It is the initial price at which a stock is bought and sold at the start of the trading day.

High: The highest price at which a security trades during the trading day. It indicates the maximum price at which the stock was bought.

Low: The lowest price at which a security trades during the trading day. It indicates the minimum price at which the stock was sold.

Close: The last price at which a security trades during the regular trading hours on a given trading day. It is often considered the most important price of the day because it is used as a reference point for many indicators and calculations.

Adj Close (Adjusted Close): The closing price after adjustments for all applicable splits and dividend distributions. This value is used to reflect the stock's value accurately after corporate actions such as stock splits, dividends, and rights offerings.

Volume: The total number of shares or contracts traded for the security during the trading day. It indicates the trading activity and liquidity of the security.
"""

# Plotting the Close Price of the stock
plt.figure(figsize=(14, 7))
plt.plot(data['Close'], label='AAPL Close Price', color='b')
plt.title('Apple Inc. (AAPL) Close Price')
plt.xlabel('Date')
plt.ylabel('Close Price (USD)')
plt.legend()
plt.grid(True)
plt.show()

"""Attempt Question(for self evaluation):

Write a Python script to download historical stock data for Microsoft Corporation (ticker: MSFT) from Yahoo Finance for the period from January 1, 2021, to December 31, 2023. The script should:

Install the necessary libraries (numpy, pandas, yfinance, matplotlib, seaborn).
Download the data for the given period.
Extract the Open, High, Low, Close, Adj Close, and Volume columns.
Plot the daily Opening Prices vs Time graph for the entire period.
"""

ticker = 'MSFT'  # Apple Inc. stock as an example
start_date = '2021-01-01'
end_date = '2023-12-31'
data = yf.download(ticker, start=start_date, end=end_date)

# Display the first 5 rows of the data
data.head()

plt.figure(figsize=(14, 7))
plt.plot(data['Open'], label='MSFT Open Price', color='b')
plt.title('MSFT Open Price')
plt.xlabel('Time')
plt.ylabel('Open Price (USD)')
plt.legend()
plt.grid(True)
plt.show()